import {EAS_CONTRACT_ABI} from "./abi"
import {
  SEPOLIA_EAS_CONTRACT_ADDRESS,
  SEPOLIA_SCHEMA_ID,
  BASE_SEPOLIA_EAS_CONTRACT_ADDRESS,
  BASE_SEPOLIA_SCHEMA_ID,
} from "./contracts"

export const CONTRACT_CONFIG = {
  84532: {
    EAS_CONTRACT_ADDRESS: BASE_SEPOLIA_EAS_CONTRACT_ADDRESS,
    SCHEMA_ID: BASE_SEPOLIA_SCHEMA_ID,
    EAS_CONTRACT_ABI: EAS_CONTRACT_ABI
  },
  11155111: {
    EAS_CONTRACT_ADDRESS:SEPOLIA_EAS_CONTRACT_ADDRESS,
    SCHEMA_ID: SEPOLIA_SCHEMA_ID,
    EAS_CONTRACT_ABI: EAS_CONTRACT_ABI
  }
}
