import {EAS_CONTRACT_ABI} from "./abi"
import {
  SEPOLIA_EAS_CONTRACT_ADDRESS,
  SEPOLIA_SCHEMA_ID,
  BASE_SEPOLIA_EAS_CONTRACT_ADDRESS,
  BASE_SEPOLIA_SCHEMA_ID,
  ARBITRUM_SCHEMA_ID,
  ARBITRUM_EAS_CONTRACT_ADDRESS,
  CELO_SCHEMA_ID,
  CELO_EAS_CONTRACT_ADDRESS
} from "./contracts"

export const CONTRACT_CONFIG = {
  84532: {
    EAS_CONTRACT_ADDRESS: BASE_SEPOLIA_EAS_CONTRACT_ADDRESS,
    SCHEMA_ID: BASE_SEPOLIA_SCHEMA_ID,
    EAS_CONTRACT_ABI: EAS_CONTRACT_ABI
  },
  11155111: {
    EAS_CONTRACT_ADDRESS:SEPOLIA_EAS_CONTRACT_ADDRESS,
    SCHEMA_ID: SEPOLIA_SCHEMA_ID,
    EAS_CONTRACT_ABI: EAS_CONTRACT_ABI
  },
  42161: {
    EAS_CONTRACT_ADDRESS: ARBITRUM_EAS_CONTRACT_ADDRESS,
    SCHEMA_ID: ARBITRUM_SCHEMA_ID,
  },
  42220: {
    EAS_CONTRACT_ADDRESS:CELO_EAS_CONTRACT_ADDRESS,
    SCHEMA_ID: CELO_SCHEMA_ID,
  }
}
